// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzad0gqs3GS966AB7N2ygJB9p5x8P35kk',
    appId: '1:692390952269:web:75d0fbd74c85bf48e6cb04',
    messagingSenderId: '692390952269',
    projectId: 'chat-app-a4212',
    authDomain: 'chat-app-a4212.firebaseapp.com',
    storageBucket: 'chat-app-a4212.appspot.com',
    measurementId: 'G-WK2W47EP52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC87GBDsTpxX0fKkjoATKgJWLaFl0P5eGA',
    appId: '1:692390952269:android:a4bc7d91128773a5e6cb04',
    messagingSenderId: '692390952269',
    projectId: 'chat-app-a4212',
    storageBucket: 'chat-app-a4212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEj8ubkR1qW_mN8f6ClAelvYk7K4MfUIg',
    appId: '1:692390952269:ios:07790e68cdd58ef3e6cb04',
    messagingSenderId: '692390952269',
    projectId: 'chat-app-a4212',
    storageBucket: 'chat-app-a4212.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEj8ubkR1qW_mN8f6ClAelvYk7K4MfUIg',
    appId: '1:692390952269:ios:430bca50a724080ae6cb04',
    messagingSenderId: '692390952269',
    projectId: 'chat-app-a4212',
    storageBucket: 'chat-app-a4212.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
